// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/blocks/args': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blocks/args').default>>>>
    }
    '/api/blocks/list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blocks/list').default>>>>
    }
    '/api/data/list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data/list').default>>>>
    }
    '/api/pipeline/load': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pipeline/load.get').default>>>>
    }
    '/api/pipeline/run': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pipeline/run.post').default>>>>
    }
    '/api/pipeline/save': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pipeline/save.post').default>>>>
    }
    '/api/results/:id/:name': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/results/[id]/[name].get').default>>>>
    }
    '/api/results/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/results/[id]/index.get').default>>>>
    }
    '/api/results/list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/results/list').default>>>>
    }
    '/api/schema/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/schema/[id].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}