# The URL the site will be built for
base_url = "https://spade.app"

title = "Spade"
description = "A data processing system for massive data with first-class geospatial support"
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown.highlighting]
theme = "github-dark"

[extra]
site_tagline = "Data processing at scale. Built for geospatial."
github_url = "https://github.com/spade-dev/spade"
docs_url = "https://docs.spade.app"
