# Spade Documentation Site
base_url = "https://docs.spade.app"
title = "Spade Documentation"
description = "Documentation for Spade, a data processing system for massive data with first-class geospatial support."
default_language = "en"
generate_feeds = false
minify_html = true
compile_sass = true
build_search_index = true

[search]
index_format = "elasticlunr_json"

[markdown.highlighting]
theme = "nord"

[extra]
docs_version = "1.0"
product_url = "https://spade.app"
github_repo = "https://github.com/spade-dev/spade"
